PIDdata=csvread(".\PIDresult.csv",1,0);
S=PIDdata(:,2);
T=PIDdata(:,5);
acc=PIDdata(:,7);
v=PIDdata(:,4);
plot(S,v);
hold on
xgbdata=csvread(".\xgboostresult.csv",1,0);
S=xgbdata(:,2);
T=xgbdata(:,5);
acc=xgbdata(:,7);
v=xgbdata(:,4);
plot(S,v);
sldata=csvread(".\sl.csv",1,0);
S=sldata(:,2);
S=S-35;
sl=sldata(:,3);
plot(S,sl);
legend("PID","xgboost","speedlimit")
